version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: rlaza
      POSTGRES_PASSWORD: rlaza
      POSTGRES_DB: olympus
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
